### PR TITLE
Removed version number from vite client script

### PR DESCRIPTION
**Pull request by Furo42**
Fixes the issue with the undefined __SERVER_HOST__ variable in the browser console.

### CODE REVIEW

**Comment by mandrasch** [comment]
Cool, thanks! I'll try and approve it in the next days! Cheers!

**Comment by Furo42** [comment]
You're welcome!

I would also like to note that this is not just a beauty correction.
If you remove the import of the Sass file in the app.js file, the connection to the vite client doesn't work anymore.
This is the reason why I became aware of this error.
By removing the version number the connection works, even without importing a styling.

But I'm not a Vite expert so I don't know why this error occurs only when no styling is imported.

**Comment by mandrasch** [comment]
> You're welcome!
> 
> I would also like to note that this is not just a beauty correction. If you remove the import of the Sass file in the app.js file, the connection to the vite client doesn't work anymore. This is the reason why I became aware of this error. By removing the version number the connection works, even without importing a styling.
> 
> But I'm not a Vite expert so I don't know why this error occurs only when no styling is imported.

Thanks for detailed explanation, much appreciated! 👍  (No vite expert either, just trying to get things working ;-))

**Comment by mandrasch** [comment]
Thanks very much for the PR, wouldn't have guessed that the version number of WP enqueue is causing this. 

(Maybe I'll also find time to convert this repo to use https://roots.io/bedrock/ in future, would be more efficient I guess).

**Pull request merged**
